name: Lint proto
on:
  push:
    paths:
      - "**.proto"
      - ".github/workflows/lint.yml"
jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
